version: "3.9"
services:
  postgresql:
    image: bitnami/postgresql:14
    volumes:
      - ./docker_volumes/postgresql:/bitnami/postgresql
    ports:
      - "5001:5432"
    environment:
      POSTGRESQL_USER: samyeung
      POSTGRESQL_PASSWORD: samyeung
    restart: always
  cms-backend:
    depends_on:
      - postgresql
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: postgresql
      DATABASE_PORT: 5432
      DATABASE_USERNAME: samyeung
      DATABASE_PASSWORD: samyeung
      DATABASE_DATABASE: cms
      AUTH_PRIVATE_KEY_PATH: '/usr/src/app/src/storage/auth-private.pem'
      AUTH_PUBLIC_KEY_PATH: '/usr/src/app/src/storage/auth-public.pem'
      AUTH_PRIVATE_JWT_EXPIRES_IN: '30' #Min
      AUTH_REFRESH_TOKEN_IN: '1' #Month